name: 'Terraform-plan'

on:
    push:
        branches: 'main'

jobs:
    terraform-test:
        name: 'Terraform Test'
        runs-on: ubuntu-latest

        steps:
            # Checkout the repository to the GitHub Actions runner
            - name: Checkout code
              uses: actions/checkout@v3

            # Install the latest version of Terraform CLI and configure the Terraform CLI configuration file with a Terraform Cloud user API token
            - name: Setup Terraform
              uses: hashicorp/setup-terraform@v2

            - name: Install Azure CLI
              run: |
                  curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash

            # Login to Azure
            - name: Login to Azure
              uses: azure/login@v1
              with:
                  creds: ${{ secrets.AZURE_CREDENTIALS }}

            # Initialize a new or existing Terraform working directory by creating initial files, loading any remote state, downloading modules, etc.
            - name: Terraform Init
              run: terraform init

            # Checks that all Terraform configuration files adhere to a canonical format
            - name: Terraform Format
              run: terraform fmt

            # Validate that all Terraform configuration files are valid
            - name: Terraform Validate
              run: terraform validate
