version: '3.8'
services:
    vote:
        container_name: vote
        command: gunicorn -w 4 -b 0.0.0.0 vote:app
        build:
            dockerfile: ./vote/Dockerfile
        ports:
            - '5000:80'
        restart: on-failure
        networks:
            - frontend
            - backend

    result:
        container_name: result
        build:
            dockerfile: ./result/Dockerfile
        ports:
            - '5001:80'
        restart: on-failure
        networks:
            - frontend
            - backend

    worker:
        container_name: worker
        build:
            dockerfile: ./worker/Dockerfile
        restart: on-failure
        networks:
            - backend

    redis:
        container_name: redis
        image: redis
        networks:
            - backend

    postgres:
        container_name: db
        image: postgres
        networks:
            - backend
        environment:
            - POSTGRES_PASSWORD=postgres
            - POSTGRES_USER=postgres
        volumes:
            - pgdata:/var/lib/postgresql/data

volumes:
    pgdata:
networks:
    frontend:
    backend:
