version: '3.8'

services:
    resellerapp:
        build:
            dockerfile: Dockerfile
        ports:
            - '8080:8080'
        depends_on:
            - mysql
        environment:
            - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/resellerappdb
            - SPRING_DATASOURCE_USERNAME=root
            - SPRING_DATASOURCE_PASSWORD=my-secret-pw
        networks:
            - backend

    mysql:
        image: mysql:8.0
        ports:
            - '3306:3306'
        environment:
            - MYSQL_ROOT_PASSWORD=my-secret-pw
            - MYSQL_DATABASE=resellerappdb
            - MYSQL_USER=user
            - MYSQL_PASSWORD=userpass
        volumes:
            - mysql-data:/var/lib/mysql
        networks:
            - backend

networks:
    backend:

volumes:
    mysql-data:
